/*
 * Graphics library demo.
 * Draws a spinning cube in wireframe and filled modes.
 * It will be difficult to fit more than that in 6kB RAM
 *  (not impossible though, see what the demoscene can do in 4kB...)
 */ 

#include <femtorv32.h>

/*
 * Generated by TOOLS/make_sintab.c
 */
int sintab[64] = {
    0,6423,12785,19023,25079,30892,36409,41574,46340,50659,54490,57796,60546,62713,64275,
    65219,65535,65219,64275,62713,60546,57796,54490,50659,46340,41574,36409,30892,25079,
    19023,12785,6423,0,-6423,-12785,-19023,-25079,-30892,-36409,-41574,-46340,-50659,
    -54490,-57796,-60546,-62713,-64275,-65219,-65535,-65219,-64275,-62713,-60546,-57796,
    -54490,-50659,-46340,-41574,-36409,-30892,-25079,-19023,-12785,-6423
};

int vertices[8][3] = {
    {-1024,-1024,-1024},
    {-1024,-1024, 1024},
    {-1024, 1024,-1024},
    {-1024, 1024, 1024},    
    { 1024,-1024,-1024},
    { 1024,-1024, 1024},
    { 1024, 1024,-1024},
    { 1024, 1024, 1024}
};    

char faces[6][4] = {
    {0,2,6,4},
    {3,1,5,7},
    {1,0,4,5},
    {2,3,7,6},
    {1,3,2,0},
    {4,6,7,5}
};

uint16_t colors[6] = {
    GL_RGB(255,0,0),
    GL_RGB(0,255,0),
    GL_RGB(0,0,255),
    GL_RGB(255,255,0),
    GL_RGB(255,0,255),
    GL_RGB(0,255,255)
};

/*
// This (unused) function commented-out, it increases
// the code segment size, then we got a stack crash
// (we are really at the limit of the 6kB space...)
void rot_z(int a, int in[8][3], int out[8][3]) {
    int s = sintab[a & 63];
    int c = sintab[(a+16) & 63];    
    for(int i=0; i<8; ++i) {
	int x = in[i][0];
	int y = in[i][1];
	out[i][0] = ( c*x + s*y) >> 16;
	out[i][1] = (-s*x + c*y) >> 16;	
    }
}
*/

void rot_x(int a, int in[8][3], int out[8][3]) {
    int s = sintab[a & 63];    
    int c = sintab[(a+16) & 63];    
    for(int i=0; i<8; ++i) {
	int y = in[i][1];
	int z = in[i][2];
	out[i][1] = ( c*y + s*z) >> 16;
	out[i][2] = (-s*y + c*z) >> 16;	
    }
}

void rot_y(int a, int in[8][3], int out[8][3]) {
    int s = sintab[a & 63];    
    int c = sintab[(a+16) & 63];    
    for(int i=0; i<8; ++i) {
	int z = in[i][2];
	int x = in[i][0];
	out[i][2] = ( c*z + s*x) >> 16;
	out[i][0] = (-s*z + c*x) >> 16;	
    }
}

void init_points() {
    for(int v=0; v<8; ++v) {
	vertices[v][2] = (v & 1) ? 1024 : -1024;
	vertices[v][1] = (v & 2) ? 1024 : -1024;
	vertices[v][0] = (v & 4) ? 1024 : -1024;	
    }
}

int main() {
    GL_init();
    GL_polygon_mode(GL_POLY_LINES);
    GL_clear();
    int vrtx[8];
    int frame = 0;
    
    for(;;) {
	/*
	 * Need to do that every period, because
	 * the lack of precision of my sine table
	 * makes things drift about a while...
	 */
	if(!(frame & 63)) {
	    init_points();
	}
	++frame;
        int scaling = (sintab[frame&63]>>8)+400;
	
	// Too big to fit in 6k, wireframe mode
	// causes stack crash... (worked before,
	// but I did put additional stuff in
	// libfemtorv32, this is why...)
	int filled = 1; // (frame & (1 << 6)); 
	rot_x(1, vertices, vertices);
	rot_y(1, vertices, vertices);
	
	if(!filled) {
	    GL_clear();
	}

	if(!filled) {
	    GL_polygon_mode(GL_POLY_LINES);	    	    
	    GL_culling_mode(GL_BACK_FACE);	
	    for(int f=0; f<6; ++f) {
		for(int lv=0; lv<4; ++lv) {
		    int v = faces[f][lv];
		    vrtx[2*lv]   = 64+vertices[v][0]*scaling/8192;
		    vrtx[2*lv+1] = 64+vertices[v][1]*scaling/8192;
		}
		GL_fill_poly(4, vrtx, GL_RGB(100,100,100));
	    }
	}
	
	GL_culling_mode(GL_FRONT_FACE);
	for(int f=0; f<6; ++f) {
	    for(int lv=0; lv<4; ++lv) {
		int v = faces[f][lv];		
		vrtx[2*lv]   = 64+vertices[v][0]*scaling/8192;
		vrtx[2*lv+1] = 64+vertices[v][1]*scaling/8192;
	    }
	    if(filled) {
		GL_polygon_mode(GL_POLY_FILL);
		GL_fill_poly(4, vrtx, colors[f]);
		GL_polygon_mode(GL_POLY_LINES);	    
		GL_fill_poly(4, vrtx, GL_RGB(0,0,0));
	    } else {
		GL_fill_poly(4, vrtx, GL_RGB(255,255,255));		
	    }
	}
	delay(15);
    }
}
