include ../makefile.inc 

ALL_PROGRAMS= cube.elf FGA_test.elf gfx_demo.elf gfx_test.elf hello.elf imgui_cup.elf \
              imgui_doom.elf imgui_road.elf imgui_tunnel.elf life_led_matrix.elf \
              malloc_test.elf mandelbrot.elf mandel_float.elf riscv_logo_2.elf \
              riscv_logo.elf sieve.elf spirograph.elf ST_NICCC.elf ST_NICCC_spi_flash.elf \
              sysconfig.elf test_buttons.elf test_font_OLED.elf \
              test_spi_flash.elf test_spi_sdcard.elf tinyraytracer.elf tty_OLED.elf


all:
	@echo "Please specify target (progname.elf, progname.bin, progname.hex) or 'everything'"

everything: $(ALL_PROGRAMS)

