/*
 * Graphics library demo.
 */ 

#include <femtorv32.h>

/*
 * Generated by TOOLS/make_sintab.c
 */

int sintab[64] = {
   0,25,49,74,97,120,142,162,181,197,212,225,236,244,251,254,
   256,254,251,244,236,225,212,197,181,162,142,120,97,74,49,25,
   0,-25,-49,-74,-97,-120,-142,-162,-181,-197,-212,-225,-236,-244,
   -251,-254,-256,-254,-251,-244,-236,-225,-212,-197,-181,-162,
   -142,-120,-97,-74,-49,-25
};

int main() {
    GL_init();
    GL_clear();
    int frame;

    for(;;) {
	int pts[8];

	if(frame & (1 << 6)) {
	    GL_clear();
	}
	int a = frame << 1;
        int scaling = sintab[(frame >> 2)&63]+400;
	
	int Ux = (sintab[a & 63] * scaling) >> 11;         
        int Uy = (sintab[(a + 16) & 63] * scaling) >> 11;
	int Vx = -Uy;
	int Vy =  Ux;
	
	pts[0] = 64 + Ux + Vx; 
	pts[1] = 64 + Uy + Vy; 

	pts[2] = 64 - Ux + Vx; 
	pts[3] = 64 - Uy + Vy; 

	pts[4] = 64 - Ux - Vx; 
	pts[5] = 64 - Uy - Vy; 

	pts[6] = 64 + Ux - Vx; 
	pts[7] = 64 + Uy - Vy; 
	
	uint16_t color = frame; 

	GL_fill_poly(4, pts, color);
	GL_polygon_mode((frame & (1 << 5)) ? GL_POLY_LINES : GL_POLY_FILL);
	
        delay(50);
	
	++frame;
    }
}
