/* 
 * Do not edit this file, it was generated by gen_pll.sh
 * 
 *   FPGA kind      : ICE40
 *   Input frequency: 100 MHz
 */

 module femtoPLL #(
    parameter freq = 40
 ) (
    input wire pclk,
    output wire clk
 );

   SB_PLL40_PAD pll (
      .PACKAGEPIN(pclk),
      .PLLOUTCORE(clk),
      .RESETB(1'b1),
      .BYPASS(1'b0)
   );
   defparam pll.FEEDBACK_PATH="SIMPLE";
   defparam pll.PLLOUT_SELECT="GENCLK";
   generate
     case(freq)
     16: begin
      defparam pll.DIVR = 4'b0011;
      defparam pll.DIVF = 7'b0101000;
      defparam pll.DIVQ = 3'b110;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     20: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0011111;
      defparam pll.DIVQ = 3'b101;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     24: begin
      defparam pll.DIVR = 4'b0010;
      defparam pll.DIVF = 7'b0010110;
      defparam pll.DIVQ = 3'b101;
      defparam pll.FILTER_RANGE = 3'b011;
     end
     25: begin
      defparam pll.DIVR = 4'b0000;
      defparam pll.DIVF = 7'b0000111;
      defparam pll.DIVQ = 3'b101;
      defparam pll.FILTER_RANGE = 3'b101;
     end
     30: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0101111;
      defparam pll.DIVQ = 3'b101;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     35: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0011011;
      defparam pll.DIVQ = 3'b100;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     40: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0011111;
      defparam pll.DIVQ = 3'b100;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     45: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0100011;
      defparam pll.DIVQ = 3'b100;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     48: begin
      defparam pll.DIVR = 4'b0010;
      defparam pll.DIVF = 7'b0010110;
      defparam pll.DIVQ = 3'b100;
      defparam pll.FILTER_RANGE = 3'b011;
     end
     50: begin
      defparam pll.DIVR = 4'b0000;
      defparam pll.DIVF = 7'b0000111;
      defparam pll.DIVQ = 3'b100;
      defparam pll.FILTER_RANGE = 3'b101;
     end
     55: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0101011;
      defparam pll.DIVQ = 3'b100;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     60: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0101111;
      defparam pll.DIVQ = 3'b100;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     65: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0110011;
      defparam pll.DIVQ = 3'b100;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     66: begin
      defparam pll.DIVR = 4'b1000;
      defparam pll.DIVF = 7'b1011110;
      defparam pll.DIVQ = 3'b100;
      defparam pll.FILTER_RANGE = 3'b001;
     end
     70: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0011011;
      defparam pll.DIVQ = 3'b011;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     75: begin
      defparam pll.DIVR = 4'b0000;
      defparam pll.DIVF = 7'b0000101;
      defparam pll.DIVQ = 3'b011;
      defparam pll.FILTER_RANGE = 3'b101;
     end
     80: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0011111;
      defparam pll.DIVQ = 3'b011;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     85: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0100001;
      defparam pll.DIVQ = 3'b011;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     90: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0100011;
      defparam pll.DIVQ = 3'b011;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     95: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0100101;
      defparam pll.DIVQ = 3'b011;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     100: begin
      defparam pll.DIVR = 4'b0000;
      defparam pll.DIVF = 7'b0000111;
      defparam pll.DIVQ = 3'b011;
      defparam pll.FILTER_RANGE = 3'b101;
     end
     105: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0101001;
      defparam pll.DIVQ = 3'b011;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     110: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0101011;
      defparam pll.DIVQ = 3'b011;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     115: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0101101;
      defparam pll.DIVQ = 3'b011;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     120: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0101111;
      defparam pll.DIVQ = 3'b011;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     125: begin
      defparam pll.DIVR = 4'b0000;
      defparam pll.DIVF = 7'b0001001;
      defparam pll.DIVQ = 3'b011;
      defparam pll.FILTER_RANGE = 3'b101;
     end
     130: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0110011;
      defparam pll.DIVQ = 3'b011;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     135: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0011010;
      defparam pll.DIVQ = 3'b010;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     140: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0011011;
      defparam pll.DIVQ = 3'b010;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     150: begin
      defparam pll.DIVR = 4'b0000;
      defparam pll.DIVF = 7'b0000101;
      defparam pll.DIVQ = 3'b010;
      defparam pll.FILTER_RANGE = 3'b101;
     end
     160: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0011111;
      defparam pll.DIVQ = 3'b010;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     170: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0100001;
      defparam pll.DIVQ = 3'b010;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     180: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0100011;
      defparam pll.DIVQ = 3'b010;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     190: begin
      defparam pll.DIVR = 4'b0100;
      defparam pll.DIVF = 7'b0100101;
      defparam pll.DIVQ = 3'b010;
      defparam pll.FILTER_RANGE = 3'b010;
     end
     200: begin
      defparam pll.DIVR = 4'b0000;
      defparam pll.DIVF = 7'b0000111;
      defparam pll.DIVQ = 3'b010;
      defparam pll.FILTER_RANGE = 3'b101;
     end
     default: UNKNOWN_FREQUENCY unknown_frequency();
     endcase
  endgenerate   

endmodule  
