/*
 * Graphics library demo.
 */ 

#include "lite_fb.h"

#include <stdio.h>
#include <libbase/uart.h>
#include <libbase/console.h>

/*
 * Generated by TOOLS/make_sintab.c
 */

int sintab[64] = {
   0,25,49,74,97,120,142,162,181,197,212,225,236,244,251,254,
   256,254,251,244,236,225,212,197,181,162,142,120,97,74,49,25,
   0,-25,-49,-74,-97,-120,-142,-162,-181,-197,-212,-225,-236,-244,
   -251,-254,-256,-254,-251,-244,-236,-225,-212,-197,-181,-162,
   -142,-120,-97,-74,-49,-25
};

int main(void) {
    fb_init();
    int frame;
    int comp = 0;
   
    for(;;) {
	int pts[8];

	//if(frame & (1 << 6)) {
	//    fb_clear();
	//}
       
	int a = frame << 1;
        int scaling = sintab[(frame >> 2)&63]+400;
	
	int Ux = (sintab[a & 63] * scaling) >> 10;
        int Uy = (sintab[(a + 16) & 63] * scaling) >> 10;
	int Vx = -Uy;
	int Vy =  Ux;
	
	pts[0] = (FB_WIDTH/2)  + Ux + Vx; 
	pts[1] = (FB_HEIGHT/2) + Uy + Vy; 

	pts[2] = (FB_WIDTH/2)  - Ux + Vx; 
	pts[3] = (FB_HEIGHT/2) - Uy + Vy; 

	pts[4] = (FB_WIDTH/2)  - Ux - Vx; 
	pts[5] = (FB_HEIGHT/2) - Uy - Vy; 

	pts[6] = (FB_WIDTH/2)  + Ux - Vx; 
	pts[7] = (FB_HEIGHT/2) + Uy - Vy; 
	
       
        if((frame & 1023) == 1023) {
	   comp = (comp + 1)%3;
	}
       
       
	uint32_t color = fb_RGB((comp == 0)*frame,(comp == 1)*frame,(comp == 2)*frame); 

        fb_fill_poly(4, pts, color);
	fb_set_poly_mode((frame & (1 << 5)) ? FB_POLY_LINES : FB_POLY_FILL);
	
        //delay(50);
	
	++frame;
        if (readchar_nonblock()) {
	   getchar();
	   break;
       }
    }
}
