libs: 
	  (cd LIBFEMTORV32;  make clean all) # Compile hardware support lib
	  (cd LIBFEMTOC;     make clean all) # Compile lib with printf() replacement function
	  (cd CRT_BAREMETAL; make clean all) # Compile C runtime for baremetal
	  @echo ==== Generated femtorv32 libs.
	  
