/*
 * Graphics library demo.
 */ 

#include <femtorv32.h>

/*
 * Generated by TOOLS/make_sintab.c
 */

int sintab[64] = {
   0,25,49,74,97,120,142,162,181,197,212,225,236,244,251,254,
   256,254,251,244,236,225,212,197,181,162,142,120,97,74,49,25,
   0,-25,-49,-74,-97,-120,-142,-162,-181,-197,-212,-225,-236,-244,
   -251,-254,-256,-254,-251,-244,-236,-225,-212,-197,-181,-162,
   -142,-120,-97,-74,-49,-25
};

int main() {
    GL_init();
    GL_clear();    
    int frame;
    for(;;) {
	int a = frame;
        int scaling = sintab[(frame >> 1)&63]+400;
	
	int Ux = (sintab[a & 63] * scaling) >> 12;         
        int Uy = (sintab[(a + 16) & 63] * scaling) >> 12;
	int Vx = -Uy;
	int Vy =  Ux;
	
	int x1 = 64 + Ux + Vx; 
	int y1 = 64 + Uy + Vy; 

	int x2 = 64 + Ux - Vx; 
	int y2 = 64 + Uy - Vy; 

	int x3 = 64 - Ux - Vx; 
	int y3 = 64 - Uy - Vy; 

	int x4 = 64 - Ux + Vx; 
	int y4 = 64 - Uy + Vy; 
	
	
	GL_line(x1,y1,x2,y2,frame);
	GL_line(x2,y2,x3,y3,frame);
	GL_line(x3,y3,x4,y4,frame);
	GL_line(x4,y4,x1,y1,frame);
	
	++frame;
    }
}
